### ISSUE TITLE
Copying multiple contexts ?

### ISSUE THREAD

**Issue by jhuet** [particle-php/Validator#110]
Say i have a username and a password field and i want to have both a backend ajax validation on each field and a final validation of both fields on submit. Of course i'd like to do so without having to re-declare the rules for each field in the single and multi validation.

The best solution i thought i could come up with is : 

```php
    $validator->context('field.username', function(Validator $context) {
        $context
            ->required('username')
            ->lengthBetween(6, null)
        ;
    });

    $validator->context('field.password', function(Validator $context) {
        $context
            ->required('password')
            ->lengthBetween(8, null)
        ;
    });

    $validator->context('insert', function(Validator $context) {
        $context
            copyContext('field.username')
            copyContext('field.password')
        ;
    });
```

Unfortunatly, copies of contextes don't cumulate but erase each others. So my question is, am i thinking this right ? Is there another way to do this ? Or is it worth heading into that direction and thus changing ``copyContext()`` so it allows this scenario ?

**Comment by RickvdStaaij** [comment]
Hello @jhuet,

I've been trying to understand what you're doing, but you say you want to do ajax validation per field? I have a completely different suggestion for you, might help you out:

Since Validator 2.0 we support an [output method](https://github.com/particle-php/Validator/blob/master/docs/output.md). With this method you could create a json array containing all the validation rules. If you echo that json array to an hidden input field (for example) you could let a front-end validation library pick that up and take over your validation on the front end. This way you have:

* Instant front-end validation
* php validation on submit

In the future we will provide such a front-end library which makes this work with particle out of the box, but i'm not expecting that very soon.

What do you think about this solution?

**Comment by jhuet** [comment]
Hi @RickvdStaaij, thanks for you answer. Sorry if i'm not being clear enough here but my concern is not about the format of the validation and how it's gonna be consumed by the client :) My concern is about not wanting to repeat my validation rules if i do a single field validation on an ajax call and another global validation containing all the form fields to validate at once.

I think i got lost in conception here because i was trying to put single and global validation rules into a single `Validator`. I thought i could re-use the single validation rules and combine them to do a global validation but i guess i'm gonna have to create multiple instances of `Validator` and handle the re-use of rules outside of it.

Something like that :

```php
    public function validateUsername($username)
    {
        $validator = $this->ruleUsername(new Validator());

        return $validator->validate(['username' => $username]);
    }

    protected function ruleUsername($validator)
    {
        $validator
            ->required('username')
            ->lengthBetween(6, null)
        ;

        return $validator;
    }

    public function validatePassword($password)
    {
        $validator = $this->ruleUsername(new Validator());

        return $validator->validate(['password' => $password]);
    }

    protected function rulePassword($validator)
    {
        $validator
            ->required('password')
            ->lengthBetween(8, null)
        ;

        return $validator;
    }

    public function validateAll($values)
    {
        $validator = new Validator();
        $this->ruleUsername($validator);
        $this->rulePassword($validator);

        return $validator->validate($values);
    }
```

**Comment by jhuet** [comment]
The thing here is that it really feels like i'm re-using the concept of contextes by doing that. My `validateAll` method is like a *all* `context`. I could make another one called `validateInsert` and use it only for inserts.

I'm coming back to my 1st idea here, i think we should be able to copy multiple contextes into one. Unless you see another way to combine both single field validation and multiple validations without duplicating the validation rules of these fields ?

**Comment by RickvdStaaij** [comment]
@jhuet I don't see a better way of doing it, but I also don't think its too bad to define copy over some validations for an update or an insert. Combining the context like you do would be a solution, but I don't think it's getting any cleaner than that. I'm closing this issue now, feel free to reopen it if you have any additions or idees
