### ISSUE TITLE
[Feature Request] Purely sequential array validation

### ISSUE THREAD

**Issue by castarco** [particle-php/Validator#126]
It would be nice to allow Particle Validator to check if arrays are sequential lists or not. It's not the same having an ordered list than having an associative array, which is technically equivalent to a "dictionary" or a "map". 

I want to add this feature by myself in a few days, but I'm writing this issue to "document" it and allow other people to discuss about whether this is a good idea or not.

**Comment by RickvdStaaij** [comment]
@castarco so you would like to check if the array keys are actually like `$array[0], $array[1], $array[2]`? If you still want to add it, go for it! :wink: I haven't heard of any other people who would like to use this though, so I'm going to close the issue. Feel free to re-open it (or just implement it and push the PR) if you feel that it will be off value to other as well :)
