### ISSUE TITLE
Zero dependencies yet it depends on two packages

### ISSUE THREAD

**Issue by jaytaph** [particle-php/Validator#127]
### What

It depends on two packages in the `composer.json`:

      "byrokrat/checkdigit": "^1.0",
      "giggsey/libphonenumber-for-php": "^7.2"

### What is expected

zero dependencies :)

**Comment by RickvdStaaij** [comment]
After some consideration we've added two framework agnostic packages indeed, but you're right, the readme states otherwise. We will update this.

**Comment by berry-langerak** [comment]
[Fixed](https://github.com/particle-php/Validator/pull/128), although I haven't removed the dependencies, I simply removed the lie. I'm going to have a tinker about if we can actually get back to zero dependencies by making them optional.
