### ISSUE TITLE
Make dependencies optional

### ISSUE THREAD

**Issue by jschreuder** [particle-php/Validator#140]
### What

The byrokrat/checkdigit also requires BCMath, and is only necessary for creditcard number checks if I understand the change correctly. Similarly the other dependency is only necessary for phone numbers. Both are perfectly fine to require for those validators, but shouldn't be full requirements. You can make them optional and add them as suggestions in the composer.json file, along with an explanation why they're necessary: https://getcomposer.org/doc/04-schema.md#suggest

In the validators that require them you could check if the necessary classes exist, and throw an exception explaining the dependency if they're not installed.

### What is expected

Not having to install PHP extensions for functionality I don't use. Also keep it as small as possible, not requiring more dependencies than are absolutely necessary. And make the others suggestions.

**Comment by RickvdStaaij** [comment]
Personally, I like this suggestion a lot! :+1: We need to make it explicit in the documentation too then. @berry-langerak what do you think?

**Comment by RickvdStaaij** [comment]
I'm discussing a proper fix within my team @Enrise, please bear with me :wink:

**Comment by RickvdStaaij** [comment]
Ok I'm going to do this as following:

1. I'm going to make a v2.1 branch, where I'm going to push #141 to, and then release `v2.1.1` for that.
1. I'm also going to release `v2.2.0` with the latest work in master, and including the fix in #141

After that's done I'll close this issue.

Thanks to @rtuin and @david4worx for figuring the best way to go here, and a big thanks to @jschreuder for suggesting this ofcourse :)

**Comment by jschreuder** [comment]
And thank you for the quick response!

**Comment by RickvdStaaij** [comment]
I released [v2.1.1](https://github.com/particle-php/Validator/releases/tag/v2.1.1) and with that resolved this issue. I will try to make a 2.2.0 release today too with the latest work from `master`!
