### ISSUE TITLE
Rule Class for comparing other fields

### ISSUE THREAD

**Issue by rsandimbefore** [particle-php/Validator#146]
### What I would create

Hi, I would like to create another rule for reuse logic instead coding same logic in callbacks approach. I made success coding simple logics (using the manual to extending Particle), but when I've tried to create one rule named greaterThanDate($param), where $param is the name of field that I suppose do compare it. It not works.

### What is expected

```php
<?php

namespace B4\Validators\Rules;

use Particle\Validator\Rule;

class GreaterThanDate extends Rule
{
    const NOT_GREATER = 'CpfRule::NOT_GREATER';

    protected $messageTemplates = [
        self::NOT_GREATER => 'Data {{ name }} não é maior que data {{ field }}.',
    ];

    private $dateField;

    public function __construct($dateField) {
        $this->dateField = $dateField;
    }

    public function validate($value) {

        if ($value > $this->values[$this->dateField]) {
            return true;
        }
        return $this->error(self::NOT_GREATER);
    }

    protected function getMessageParameters()
    {
        return array_merge(parent::getMessageParameters(), [
            'field' => $this->dateField,
        ]);
    }
}
```
As you can see $this->values[$this->dateField] should be the file accessed to obtain this information, but $this->values seems to be null. In Rule class, has a protected attribute named $values that should store this information. Am I right?

**Comment by RickvdStaaij** [comment]
Hello @rsandimbefore, sorry for the late reply, I lost track of this issue.

To answer your question, on the abstract `Rule` class, there is an attribute `$values`, but when I check the code, only in the `Rule\Callback` class that value is actually filled ([here](https://github.com/particle-php/Validator/blob/master/src/Rule/Callback.php#L101)). We could change that for all classes by filling the `$values` attribute [here](https://github.com/particle-php/Validator/blob/master/src/Rule.php#L108). That explains why your `$values` attribute was `null` in your custom rule.

I hope this answered your question, and I hope the answer is not *too* late. If you have any more questions feel free to reply to this ticket or open a new one!
