### ISSUE TITLE
Is CONTRIBUTING.md outdated?

### ISSUE THREAD

**Issue by schnittstabil** [particle-php/Validator#153]
### What
I want to create some PRs for some typos and improvements, but I'm a bit confused by `.github/CONTRIBUTING.md`:
> The on-going development will take place in the `master` branch. Bug fixes should be based on the latest release branch (e.g. `v1.0`, if the bug occurs in `v1.0.0`). After this, we can merge `v1.0` back into the `master` branch to get the bug fix in the current development version.

But there is no `v2` branch!?

### What is expected

Basing PRs on the `master` branch:  I can't know if my fixes will be merged into `v1`, `v2` or both or anywhere else as well – but the bugs are in `master`, hence I want them to be fixed in `master`.

**Comment by RickvdStaaij** [comment]
Hello @schnittstabil, master is the latest version, so it represents version 2. Please push your pull requests towards the master branch :) (unless you want to do a specific fix for an old version, but that's not the case)

I will clarify this in the `CONTRIBUTING.md`, thank you for bringing this to our attention!
