### ISSUE TITLE
Method signature in docblock of extending Validator class needs correct parameters

### ISSUE THREAD

**Issue by adriansuter** [particle-php/Validator#158]
First of all, thanks for this great tool.

I have found an issue using PHPStorm IDE (version 2016.2.2).

In the docs you wrote (http://validator.particle-php.com/en/latest/extending/), the docblock for the custom Validator to be as follows:

``` php
/**
 * @method MyChain required()
 * @method MyChain optional()
 */
```

Doing this would give me the following warning message:

![clipboard01](https://cloud.githubusercontent.com/assets/3974990/19698949/98636e44-9af1-11e6-98aa-f3c237de86f0.png)

I had to change the docblock to the following in order to avoid that warning message:

``` php
/**
 * @method MyChain required($key, $name = null, $allowEmpty = false)
 * @method MyChain optional($key, $name = null, $allowEmpty = true)
 */
```

Maybe you could update the documentation.

**Comment by RickvdStaaij** [comment]
Great suggestion @adriansuter, I will make sure this gets updated soon. Also feel free to adjust it yourself in a PR, if you want the credits for it :wink:

**Comment by adriansuter** [comment]
Done. See #159

**Comment by adriansuter** [comment]
Great.
