### ISSUE TITLE
Type checking rules didn't brake the chain and it cause a fatal exception

### ISSUE THREAD

**Issue by vova07** [particle-php/Validator#174]
### What

```php
$validator
            ->required('key')
            ->string()
            ->lengthBetween(1, 255);

$result = $validator->validate(
    [
        'key' => ['string'],
    ]
);
```

### What is expected

```php
[
    'key' => [
        IsString::NOT_A_STRING => 'key must be a string,
    ],
],
```

### What actually we got

```php
PHP: Exception
strlen() expects parameter 1 to be string, array given
```

### Reason
Because the primitive rules didn't brake the chain, the `lengthBetween` rule fail because of wrong value it get to validate.

### Link to the PR with a fix
https://github.com/particle-php/Validator/pull/173

**Comment by RickvdStaaij** [comment]
This issue is now resolved in [v2.3.1](https://github.com/particle-php/Validator/releases/tag/v2.3.1). Thanks a lot @vova07!

Feel free to open another improvement issue / PR to enhance the adjustability of the break-chain boolean.

**Comment by vova07** [comment]
Thanks for your hard work!

**Comment by RickvdStaaij** [comment]
You did all the hard work though @vova07 :wink:
