### ISSUE TITLE
Packagist version

### ISSUE THREAD

**Issue by creocoder** [particle-php/Validator#176]
### What

Packagist still contains old 2.3.0 version.

### What is expected

Lastest version after release. It's possible by enabling the packagist service hook. More info: https://packagist.org/about#how-to-update-packages

**Comment by RickvdStaaij** [comment]
Hey @creocoder thanks for noticing, we set this up previously, not sure why it isn't working.

I would fix it if I could, but I don't have the access on packagist. @berry-langerak could you take a look? And maybe give me access too :wink:

**Comment by berry-langerak** [comment]
I pulled in the new version manually. It seems packagist didn't like the content of the licence in the composer.json file, will fix later. Ah, and you're now a maintainer, @RickvdStaaij

**Comment by RickvdStaaij** [comment]
Thanks @berry-langerak.

This issue is new resolved by issuing the correct licence key in the `composer.json` file :wink:
