### ISSUE TITLE
[CRITICAL] Break chain is not skipped on success validation result

### ISSUE THREAD

**Issue by vova07** [particle-php/Validator#179]
### What
In case we have a chain of rules and one of rule will have sett up brick chain, the validation will pass even with wrong data juts because the next rules will be skipped by chain.
The problem is that break chain should be considered only in case the specific rule fail but not always as it is right now. (Expecting Required rule.)

```php
$this
    ->validator
    ->required('foo')
    ->string()
    ->lengthBetween(2, 5);

$result = $this->validator->validate(['foo' => 'abcdefg']);

$isValid = $result->isValid(); // $isValid === true
```

### What is expected

```php
$isValid = $result->isValid(); // $isValid === false
```

### PR to reproduce the bug
https://github.com/particle-php/Validator/pull/178

### PR with a hot fix
https://github.com/particle-php/Validator/pull/177

**Comment by creocoder** [comment]
@berry-langerak , @RickvdStaaij Can you please look into this? Without that fix current master contains critical bug.

**Comment by RickvdStaaij** [comment]
Merged and released:

https://github.com/particle-php/Validator/releases/tag/v2.3.2

Packagist should automatically update again too.

Thanks a lot @vova07! Also thank you @creocoder for the helping hand :) :+1:
