### ISSUE TITLE
Validate empty value's type

### ISSUE THREAD

**Issue by 2e3s** [particle-php/Validator#183]
Requirements:
`[ 'field' => [] ]` is a correct value
`[ 'field' => '' ]` is an incorrect value

But I can't validate this with Particle because it breaks the chain when you specify `$validator->required($name, null, true)`. When `allowEmpty` is `false` it returns a failure on valid `[]`. Same goes for `''`.

The break is unconditional, so I can't influence it: 
https://github.com/particle-php/Validator/blob/master/src/Rule/NotEmpty.php#L93
https://github.com/particle-php/Validator/blob/master/src/Chain.php#L64

Can empty values be fixed in Particle in regards of stricter types or should another way to validate be used for such cases?

**Comment by RobQuistNL** [comment]
You could try to use `isArray` instead of `required` ? It will basically cause the check to work correctly (as `[]` will now validate, but `null` will not)

**Comment by 2e3s** [comment]
We've decided to go with less strict validation back then so it can be closed. Ideally it's better to be typed though.
