### ISSUE TITLE
Problems with lengthBetween & equals

### ISSUE THREAD

**Issue by whatTool** [particle-php/Validator#190]
### What
Hello,
I am trying to use your Validation class to validate the length of a string and compare it another string.

Here is my code 

        $v->required("newPassword")->lengthBetween(8, null);
        if($v->validate(["newPassword" => $_POST["newPassword"]])->isNotValid()){
            //error
        }else
            $newPassword = $_POST["newPassword"];

        $v->required("repeatPassword")->equals($newPassword);
        if($v->validate(["repeatPassword" => $_POST["repeatPassword"]])->isValid()){
            // continue

However, I am having difficulties getting this to work.
With my input for `newPassword` being `"1234567"` and the same for `repeatPassword`, to check if it returns my error message, however, it "bypasses" the validation of the length and goes straight to the equals, which it fails at. Even tho' both is `"1234567"`

### What is expected
I would imagine that I am doing something wrong, I just can't figure out what I'm doing wrong.

**Comment by RobQuistNL** [comment]
You might want to try the latest build, there was an issue with re-using validator chains which has since been fixed.

Also from your code it looks like you're using 2 validation calls, which is not needed (and also triggers the bug that was there: https://github.com/particle-php/Validator/pull/192);

Your code will work like this as well:

```
$v->required("newPassword")->lengthBetween(8, null);
$v->required("repeatPassword")->equals($newPassword);

$result = $v->validate(
    [
        "newPassword" => $_POST["newPassword"],
        "repeatPassword" => $_POST["repeatPassword"],
    ]
);

if ($result->isNotValid()) {
    //error
} else {
    //Valid
}
```
