### ISSUE TITLE
一个关于Url 验证的问题

### ISSUE THREAD

**Issue by denymz** [particle-php/Validator#194]
首先说一句抱歉，因为我的英语很不好。也非常感谢作者的这个项目，让我节省了很多时间！
不过今天在使用时在文档中发现了一个错误：
Link ： http://validator.particle-php.com/en/latest/rules/#url

以下是文档中的一段演示代码 ： 
$v = new Validator;
$v->required('link')->url(['ftp://', 'ftps://']); 
$v->validate(['link' => 'ftp://particle-php.com'])->isValid(); // true
$v->validate(['link' => 'http://validator.particle-php.com'])->isValid(); // false

不过这其中是存在问题的，上面这段代码的运行结果都是false；
因为在 Rule/Url.php 中的第79行 parse_url($value, PHP_URL_SCHEME) 的返回的结果中不会包括  ”://“ 

Thanks！

**Comment by RickvdStaaij** [comment]
Sorry, English please :innocent:
