### ISSUE TITLE
Add ability to override validation required <-> optional

### ISSUE THREAD

**Issue by RickvdStaaij** [particle-php/Validator#26]
When a validator is created with a required field key, it can not be overridden to optional in a different context.

```php
$v = new Validator;

$v->required('first_name')->lengthBetween(2, 30);

$v->context('update', function(Validator $context) {
    $context->optional('first_name');
});
```

Currently `first_name` will always be required, this should get changed to optional for context `update`.

**Comment by berry-langerak** [comment]
This has been fixed in PR #40.
