### ISSUE TITLE
Validate objects in addition to arrays

### ISSUE THREAD

**Issue by fireproofsocks** [particle-php/Validator#37]
Example scenario:

````
$validator = new Validator();
$validator->required('first_name')->lengthBetween(2, 20);
$obj = new stdClass();
$obj->first_name = 'Bob';
$validator->validate($obj);  
````

* Desired outcome: returns true.
* Actual outcome: "Argument 1 passed to Particle\Validator\Validator::validate() must be of the type array, object given"

**Comment by berry-langerak** [comment]
Hi @fireproofsocks. Thanks for the feedback, much appreciated. To get a clear view of what you're asking: is it only for `\stdClass` objects, or would you like it if Particle\Validator could even use getters to get the values from your objects?

**Comment by fireproofsocks** [comment]
I think it would have to be only stdClass or objects whose properties were available publicly (i.e. $obj->x and not $obj->get('x') et al).

The workaround is to do array conversion, e.g. something along the lines of:

````
$validator->validate( (array) $obj);
```

Actually, the more I think about it, the above is probably the simplest solution, and arrays would work much more easily in the nested data structures suggested in feature #28.

Given that there's a simple workaround and using arrays internally would make for implementation of #28 easier, I'm closing this -- sorry to "think out loud" in the issue tracker.

**Comment by RickvdStaaij** [comment]
No problem at all, much appreciated!

**Comment by berry-langerak** [comment]
@fireproofsocks don't apologise, I value all feedback. In response: I chose to type-hint the values to be of type `array` with a good reason: it's one of the most versatile data structures available in PHP, and it gives a well-defined interface without explicitly needing an actual interface, meaning every structure in your code can easily be transformed to array (e.g. XML, json, YAML, stdClass instances, a set of objects, etc.)

That means I was already leaning towards not adding this to the Particle\Validator library, but I do have a few suggestions to help people on their way (also if they're reading your issue later -- after all, it's a valid question):

For stdClass instances, you can simply type-cast to an array and be done with it, like you said. So:

```php
$values = new \stdClass;
$values->first_name = 'Hello';

$validator->required('first_name');
$validator->validate((array) $values);
```

If you want to validate plain old PHP objects which include setters and getters, it might be helpful to look into the [GeneratedHydrator](https://github.com/Ocramius/GeneratedHydrator) project. That helps in converting your projects' objects to an array, and from an array back to objects.

Anyway, thanks for the feedback and the interest in our library :)
