### ISSUE TITLE
problems with the datetime rule format

### ISSUE THREAD

**Issue by NickBelhomme** [particle-php/Validator#59]
# What

When specifying a format to the datetime rule it does not use it consistent.

# reproduce

```php
$validator = new \Particle\Validator\Validator();
$validator->required('myDate')->datetime('Ymd');

var_dump($validator->validate(['myDate' => '20150131'])); // true
var_dump($validator->validate(['myDate' => '2015131'])); // false expected false
var_dump($validator->validate(['myDate' => '2015125'])); // true expected false
```

# Acceptance Criteria

The date format should be really validated

when I pass 2015125 it should fail because
Ymd
Y A full numeric representation of a year, 4 digits
m Numeric representation of a month, with leading zeros
d Day of the month, 2 digits with leading zeros

**Comment by berry-langerak** [comment]
This was fixed in #63
