### ISSUE TITLE
Support nested repeating arrays.

### ISSUE THREAD

**Issue by berry-langerak** [particle-php/Validator#64]
Since v1.0.0, we've the ability to validate sub-arrays using dot-notation. This is awesome and very useful for nested arrays. However, what hasn't been covered yet is validation of repeating groups. The following would be really nice to add for v2.0.0:

```php
<?php
use Particle\Validator\Validator;

$invoices = [
    'invoices' => [
        'invoiceDate' => '2015-04-10',
        'totalPrice' => 20.00,
        'invoiceLines' => [
            [
                'description' => 'Description of line 1',
                'price' => 10.00
            ],
            [
                'description' => 'Description of line 2',
            ],
        ],
    ],
];

$v = new Validator();
$v->required('invoices')->each(function (Validator $validator) {
    $validator->required('invoicePrice');
    $validator->required('totalPrice');

    $validator->required('invoiceLines')->each(function (Validator $validator) {
        $validator->required('description');
        $validator->required('price');
    });
});

$result = $v->validate($invoices);

var_dump($result->getMessages());
/**
 * Output:
 * array(
 *    "invoices.0.invoiceLines.1.price" => "price is required and can't be empty",
 * )
 */
```

**Comment by frankdejonge** [comment]
This would be a real big plus. While no dependencies is great, I do think mtdowling's jmespath.php package would be something to look at when and if this is implemented. Same goes for the current fetching of arguments. It's formalised, cross lingual and all-round awesome.

**Comment by berry-langerak** [comment]
@frankdejonge thanks for the feedback. jmespath.php certainly does look very interesting for path resolution, I'll definitely look into it!

**Comment by berry-langerak** [comment]
This has been implemented in https://github.com/particle-php/Validator/pull/90
