### ISSUE TITLE
Url() rule is not sufficiently checking the protocol

### ISSUE THREAD

**Issue by NickBelhomme** [particle-php/Validator#68]
# What

When providing a protocol mistype the validator should spot this.

```php
$validator = new Particle\Validator\Validator();
$validator->required('myUri')->url();
var_dump($validator->validate(['myUri' => 'htdpt://someuri.com'])); // true
```

Currently the htdpt://someuri.com  returns true, but htdpt isn't a valid protocol.

# Acceptance Criteria
validate protocol as well

# tested
v1.0.4

**Comment by berry-langerak** [comment]
I think it would be sufficient if there's a default whitelist of protocols you want to support, probably `['http', 'https']`, but having the option to pass in your own whitelist (e.g. `['ftp', 'http']`). What do you think about that solution?

**Comment by NickBelhomme** [comment]
I think that would cover all the bases.

**Comment by RobQuistNL** [comment]
``htdpt://`` is a valid protocol (or scheme actually). just like ``asdf-asdfasdf-3483-asdf://`` is a valid protocol / scheme. (In the context of a URI this part is called the scheme)

You need a whitelist option instead. 

Check out https://tools.ietf.org/html/rfc3986#section-3.1

Also check out: https://github.com/Enrise/UriHelper

**Comment by NickBelhomme** [comment]
We are interested in TCP/IP protocols:
Internetprotocollen volgens het TCP/IP-model
Toepassingslaag:	DNS · FTP · Gopher · HTTP · HTTPS · IMAP · IRC · NNTP · POP3 · RTP · SIP · SMTP · SNMP · SSH · TLS/SSL · Telnet · UUCP · XMPP
Transportlaag:	DCCP · SCTP · TCP · UDP
Netwerklaag:	ARP · ICMP · IGMP · IPv4 · IPv6 · RARP
Datalinklaag:	ATM · Ethernet · FDDI · PPP · Token ring · Wifi

In this case the toepassingslaag.
And general usage will be HTTP(S)
So whitelisting http, https is sufficient. Extra can be whitelisted by providing it as a parameter.
Even the strange "asdf-asdfasdf-3483-asdf://" protocol.
99.9999% of the usage on this rule is for checking valid htttp(s) links.

**Comment by RobQuistNL** [comment]
Well, except if you're going to use it in an API for, say, Sensimity, in which case we need custom schemes to launch apps;

my-app-id://information-for-app
steam://appid20499583
about:blank

All valid schemes and URI's

**Comment by berry-langerak** [comment]
But guys, if I add an optional white list, all of your problems would be solved, right? You can optionally add steam:// about: and my-app-id:// to the white list and be done with it, where the default is just "http" and "https". So, yeah, I'll be implementing that.

**Comment by RobQuistNL** [comment]
As long as the whitelist is optional :)

**Comment by berry-langerak** [comment]
Oh my, totally forgot about this one! Will fix! :)

**Comment by berry-langerak** [comment]
Added in pull request: https://github.com/particle-php/Validator/pull/92
