### ISSUE TITLE
Messages in other languages

### ISSUE THREAD

**Issue by ramirovjr** [particle-php/Validator#75]
Are you planning on support other languages for the messages?
I would be interested in translating to pt-BR.

**Comment by RickvdStaaij** [comment]
Hello @ramirovjr,

Currently, we don't have predefined multi-language support on the planning. The default messages could be translated with the `overwriteDefaultMessages()` function. I think you'll be rewriting the default messages anyway, if you want to add truly user friendly validation messages.

Thank you for your interest though, if we decide to pick this up, I'll be sure to contact you!
