### ISSUE TITLE
UUID checks

### ISSUE THREAD

**Issue by jaytaph** [particle-php/Validator#87]
It should be possible to do check for other types of UUIDs (v1 to 5) in the UUID rule. However, there are some issues:

It's easy enough to check the version itself, but some uuid versions, like version 3 and 5, actually are hashes taken from other information (a `name` and a `namespace`). Thus, in order to validate *correctly* (not only syntaxly), this information must be passed to the rule itself (i'm sure this is possible).

Also, it would be really nice to have the rule to check not only UUIDs in their canonical format, but also takes a packed form (as an UUID is nothing more than a 128-bit number).

**Comment by berry-langerak** [comment]
Hey! Thanks for taking the time to create an issue. I think having support for different versions of UUIDs (after all, it takes a version parameter). I'll put this on the road map for v2.1.

**Comment by RickvdStaaij** [comment]
Fixed and improved thanks to @jschreuder!
