### ISSUE TITLE
Alter value before/after validation

### ISSUE THREAD

**Issue by jaapverloop** [particle-php/Validator#89]
I'm wondering whether it's possible or desired to alter a value before/after validation. For example, I would like to use this to trim a string before validating a certain length, or to cast a numeric value to a float after validation.

**Comment by RickvdStaaij** [comment]
@jaapverloop we created https://github.com/particle-php/Filter for this. The array you want to validated could be filtered before, and after your validation. We decided to do this in separate particles, to not make one particle bloated with features you might not want to use.

I hope this answered your question, if not please let us know :wink:

**Comment by jaapverloop** [comment]
Ok, thanks! I will check it out.
